<?php
require_once '../includes/auth.php';
require_once '../includes/db.php';
requireLogin();
$db = getDB();
$page_title = 'Generate Report';

// ── Date Filter ──
$from = sanitize($_GET['from'] ?? date('Y-m-01'));        // first day of this month
$to   = sanitize($_GET['to']   ?? date('Y-m-d'));         // today
$type = $_GET['type'] ?? 'sales';

$from_ts = $from . ' 00:00:00';
$to_ts   = $to   . ' 23:59:59';

// ── SALES REPORT ──
$total_revenue  = $db->query("SELECT COALESCE(SUM(total_price),0) t FROM orders WHERE order_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['t'];
$total_orders   = $db->query("SELECT COUNT(*) c FROM orders WHERE order_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['c'];
$total_paid     = $db->query("SELECT COALESCE(SUM(price),0) t FROM payments WHERE payment_status='completed' AND payment_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['t'];
$total_pending  = $db->query("SELECT COUNT(*) c FROM orders WHERE delivery_status='pending' AND order_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['c'];
$total_shipped  = $db->query("SELECT COUNT(*) c FROM orders WHERE delivery_status='shipped' AND order_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['c'];
$total_delivered= $db->query("SELECT COUNT(*) c FROM orders WHERE delivery_status='delivered' AND order_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['c'];
$total_customers= $db->query("SELECT COUNT(DISTINCT customer_id) c FROM orders WHERE order_date BETWEEN '$from_ts' AND '$to_ts'")->fetch_assoc()['c'];
$avg_order      = $total_orders > 0 ? $total_revenue / $total_orders : 0;

// ── TOP PRODUCTS ──
$top_products = $db->query("
    SELECT p.name, p.product_image, c.category_name,
           SUM(od.quantity) AS total_qty,
           SUM(od.quantity * od.product_price) AS total_rev
    FROM order_details od
    JOIN products p  ON od.product_id  = p.product_id
    JOIN categories c ON p.category_id = c.category_id
    JOIN orders o    ON od.order_id    = o.order_id
    WHERE o.order_date BETWEEN '$from_ts' AND '$to_ts'
    GROUP BY od.product_id
    ORDER BY total_qty DESC
    LIMIT 10
");
$top_rows = [];
while ($r = $top_products->fetch_assoc()) $top_rows[] = $r;

// ── TOP CUSTOMERS ──
$top_customers = $db->query("
    SELECT c.customer_name, c.customer_email,
           COUNT(o.order_id) AS order_count,
           SUM(o.total_price) AS total_spent
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    WHERE o.order_date BETWEEN '$from_ts' AND '$to_ts'
    GROUP BY o.customer_id
    ORDER BY total_spent DESC
    LIMIT 10
");
$cust_rows = [];
while ($r = $top_customers->fetch_assoc()) $cust_rows[] = $r;

// ── CATEGORY BREAKDOWN ──
$cat_sales = $db->query("
    SELECT c.category_name,
           SUM(od.quantity) AS total_qty,
           SUM(od.quantity * od.product_price) AS total_rev
    FROM order_details od
    JOIN products p  ON od.product_id  = p.product_id
    JOIN categories c ON p.category_id = c.category_id
    JOIN orders o    ON od.order_id    = o.order_id
    WHERE o.order_date BETWEEN '$from_ts' AND '$to_ts'
    GROUP BY c.category_id
    ORDER BY total_rev DESC
");
$cat_rows = [];
while ($r = $cat_sales->fetch_assoc()) $cat_rows[] = $r;
$max_rev = !empty($cat_rows) ? $cat_rows[0]['total_rev'] : 1;

// ── ORDER LIST FOR REPORT ──
$order_list = $db->query("
    SELECT o.order_id, o.order_date, o.total_price, o.delivery_status,
           c.customer_name,
           p.payment_status
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    LEFT JOIN payments p ON o.order_id = p.order_id
    WHERE o.order_date BETWEEN '$from_ts' AND '$to_ts'
    ORDER BY o.order_date DESC
");
$order_rows = [];
while ($r = $order_list->fetch_assoc()) $order_rows[] = $r;

require_once '../includes/header.php';
?>

<div class="page-head no-print">
    <div>
        <h2>Generate Report</h2>
        <p>Task 6 — Generate sales, order and product reports</p>
    </div>
    <button class="btn btn-primary" onclick="window.print()">🖨️ Print Report</button>
</div>

<!-- PRINT HEADER (only shows on print) -->
<div style="display:none" class="print-only" id="print-head">
    <h1 style="font-family:'Playfair Display',serif;font-size:26px;margin-bottom:4px">FreshMart Online Grocery</h1>
    <p style="color:#666;font-size:13px">Sales Report | Generated by: <?= sanitize(getAdminName()) ?> (<?= ucfirst(getAdminRole()) ?>) | <?= date('d M Y H:i') ?></p>
    <hr style="margin:12px 0;border-color:#ddd">
</div>

<!-- DATE FILTER -->
<div class="card no-print" style="margin-bottom:20px">
    <div class="card-body">
        <form method="GET" style="display:flex;gap:14px;align-items:flex-end;flex-wrap:wrap">
            <div class="form-group" style="margin:0">
                <label>From Date</label>
                <input type="date" name="from" value="<?= $from ?>" style="width:160px">
            </div>
            <div class="form-group" style="margin:0">
                <label>To Date</label>
                <input type="date" name="to" value="<?= $to ?>" style="width:160px">
            </div>
            <button type="submit" class="btn btn-primary">📊 Generate</button>
            <a href="reports.php" class="btn btn-ghost">Reset</a>
            <!-- Quick Presets -->
            <div style="display:flex;gap:8px;margin-left:auto;flex-wrap:wrap">
                <a href="reports.php?from=<?= date('Y-m-d') ?>&to=<?= date('Y-m-d') ?>" class="btn btn-ghost btn-sm">Today</a>
                <a href="reports.php?from=<?= date('Y-m-d',strtotime('monday this week')) ?>&to=<?= date('Y-m-d') ?>" class="btn btn-ghost btn-sm">This Week</a>
                <a href="reports.php?from=<?= date('Y-m-01') ?>&to=<?= date('Y-m-d') ?>" class="btn btn-ghost btn-sm">This Month</a>
                <a href="reports.php?from=<?= date('Y-01-01') ?>&to=<?= date('Y-m-d') ?>" class="btn btn-ghost btn-sm">This Year</a>
            </div>
        </form>
    </div>
</div>

<!-- REPORT PERIOD LABEL -->
<div style="background:var(--green-bg);border:1px solid var(--green3);border-radius:var(--radius);padding:12px 18px;margin-bottom:20px;display:flex;align-items:center;gap:10px">
    <span style="font-size:18px">📅</span>
    <div>
        <strong style="color:var(--green);font-size:14px">Report Period:</strong>
        <span style="color:var(--green);font-size:14px"> <?= date('d M Y', strtotime($from)) ?> — <?= date('d M Y', strtotime($to)) ?></span>
    </div>
</div>

<!-- ── SUMMARY STATS ── -->
<div class="report-grid">
    <div class="report-card">
        <div style="font-size:24px;margin-bottom:6px">💰</div>
        <div class="rc-label">Total Revenue</div>
        <div class="rc-value" style="color:var(--green)"><?= formatRM($total_revenue) ?></div>
    </div>
    <div class="report-card">
        <div style="font-size:24px;margin-bottom:6px">✅</div>
        <div class="rc-label">Collected (Paid)</div>
        <div class="rc-value" style="color:var(--blue)"><?= formatRM($total_paid) ?></div>
    </div>
    <div class="report-card">
        <div style="font-size:24px;margin-bottom:6px">🛍️</div>
        <div class="rc-label">Total Orders</div>
        <div class="rc-value"><?= $total_orders ?></div>
    </div>
    <div class="report-card">
        <div style="font-size:24px;margin-bottom:6px">📦</div>
        <div class="rc-label">Avg Order Value</div>
        <div class="rc-value" style="color:var(--orange)"><?= formatRM($avg_order) ?></div>
    </div>
    <div class="report-card">
        <div style="font-size:24px;margin-bottom:6px">👥</div>
        <div class="rc-label">Unique Customers</div>
        <div class="rc-value" style="color:var(--purple)"><?= $total_customers ?></div>
    </div>
    <div class="report-card">
        <div style="font-size:24px;margin-bottom:6px">🚚</div>
        <div class="rc-label">Delivery Breakdown</div>
        <div style="margin-top:6px;font-size:12px;color:var(--text2)">
            ⏳ Pending: <strong><?= $total_pending ?></strong> &nbsp;
            🚚 Shipped: <strong><?= $total_shipped ?></strong> &nbsp;
            ✅ Delivered: <strong><?= $total_delivered ?></strong>
        </div>
    </div>
</div>

<!-- ── CATEGORY BREAKDOWN ── -->
<div style="display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:18px">
    <div class="card">
        <div class="card-header"><span class="card-title">🏷️ Sales by Category</span></div>
        <div class="card-body">
            <?php if (empty($cat_rows)): ?>
            <div class="empty-state" style="padding:30px"><div class="ei">📊</div><p>No data for this period</p></div>
            <?php else: foreach ($cat_rows as $cr):
                $pct = $max_rev > 0 ? round($cr['total_rev']/$max_rev*100) : 0;
            ?>
            <div style="margin-bottom:15px">
                <div style="display:flex;justify-content:space-between;margin-bottom:5px">
                    <span style="font-size:13px;font-weight:600"><?= sanitize($cr['category_name']) ?></span>
                    <span style="font-size:13px;color:var(--green);font-weight:700"><?= formatRM($cr['total_rev']) ?></span>
                </div>
                <div class="prog-bar"><div class="prog-fill" style="width:<?= $pct ?>%;background:var(--green3)"></div></div>
                <div style="font-size:11px;color:var(--text3);margin-top:2px"><?= $cr['total_qty'] ?> units sold</div>
            </div>
            <?php endforeach; endif; ?>
        </div>
    </div>

    <!-- TOP CUSTOMERS -->
    <div class="card">
        <div class="card-header"><span class="card-title">👑 Top Customers</span></div>
        <div class="tbl-wrap">
            <table>
                <thead><tr><th>#</th><th>Customer</th><th>Orders</th><th>Spent</th></tr></thead>
                <tbody>
                <?php if (empty($cust_rows)): ?>
                <tr><td colspan="4"><div class="empty-state" style="padding:30px"><div class="ei">👥</div><p>No data</p></div></td></tr>
                <?php else: $ri=1; foreach ($cust_rows as $cr): $medals=['🥇','🥈','🥉']; ?>
                <tr>
                    <td style="font-size:16px"><?= $medals[$ri-1] ?? $ri ?></td>
                    <td>
                        <div style="font-weight:600"><?= sanitize($cr['customer_name']) ?></div>
                        <div style="font-size:11px;color:var(--text3)"><?= sanitize($cr['customer_email']) ?></div>
                    </td>
                    <td style="font-weight:700;color:var(--blue)"><?= $cr['order_count'] ?></td>
                    <td style="font-weight:700;color:var(--green)"><?= formatRM($cr['total_spent']) ?></td>
                </tr>
                <?php $ri++;endforeach;endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- ── TOP PRODUCTS ── -->
<div class="card" style="margin-bottom:18px">
    <div class="card-header"><span class="card-title">🏆 Top Selling Products</span></div>
    <div class="tbl-wrap">
        <table>
            <thead>
                <tr><th>Rank</th><th>Image</th><th>Product</th><th>Category</th><th>Units Sold</th><th>Revenue</th></tr>
            </thead>
            <tbody>
            <?php if (empty($top_rows)): ?>
            <tr><td colspan="6"><div class="empty-state" style="padding:30px"><div class="ei">📦</div><p>No product sales in this period</p></div></td></tr>
            <?php else: $ri=1; $medals=['🥇','🥈','🥉']; foreach ($top_rows as $pr): ?>
            <tr>
                <td style="font-size:18px;text-align:center"><?= $medals[$ri-1] ?? '#'.$ri ?></td>
                <td>
                    <?php if ($pr['product_image']): ?>
                    <img src="<?= sanitize($pr['product_image']) ?>" class="p-thumb" onerror="this.style.display='none'" alt="">
                    <?php else: ?><div class="p-thumb-ph">📦</div><?php endif; ?>
                </td>
                <td style="font-weight:600"><?= sanitize($pr['name']) ?></td>
                <td><span style="background:var(--green-bg);color:var(--green);padding:3px 9px;border-radius:20px;font-size:11.5px;font-weight:600"><?= sanitize($pr['category_name']) ?></span></td>
                <td><strong style="color:var(--blue);font-size:15px"><?= $pr['total_qty'] ?></strong> <span style="color:var(--text3);font-size:12px">units</span></td>
                <td><strong style="color:var(--green)"><?= formatRM($pr['total_rev']) ?></strong></td>
            </tr>
            <?php $ri++;endforeach;endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- ── FULL ORDER LIST ── -->
<div class="card">
    <div class="card-header">
        <span class="card-title">📋 Full Order List (<?= date('d M Y',strtotime($from)) ?> – <?= date('d M Y',strtotime($to)) ?>)</span>
        <span style="font-size:13px;color:var(--text3)"><?= count($order_rows) ?> orders</span>
    </div>
    <div class="tbl-wrap">
        <table>
            <thead>
                <tr><th>Order ID</th><th>Customer</th><th>Amount</th><th>Delivery</th><th>Payment</th><th>Date</th></tr>
            </thead>
            <tbody>
            <?php if (empty($order_rows)): ?>
            <tr><td colspan="6"><div class="empty-state" style="padding:30px"><div class="ei">🛍️</div><p>No orders in this period</p></div></td></tr>
            <?php else: foreach ($order_rows as $o): ?>
            <tr>
                <td><strong style="color:var(--blue)">#<?= $o['order_id'] ?></strong></td>
                <td style="font-weight:600"><?= sanitize($o['customer_name']) ?></td>
                <td><strong style="color:var(--green)"><?= formatRM($o['total_price']) ?></strong></td>
                <td><span class="badge badge-<?= $o['delivery_status'] ?>"><?= ucfirst($o['delivery_status']) ?></span></td>
                <td><span class="badge badge-<?= $o['payment_status']??'pending' ?>"><?= ucfirst($o['payment_status']??'pending') ?></span></td>
                <td style="color:var(--text3);font-size:12px"><?= date('d M Y H:i',strtotime($o['order_date'])) ?></td>
            </tr>
            <?php endforeach;endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Print Footer -->
<div style="display:none;margin-top:30px;padding-top:14px;border-top:1px solid #ddd;font-size:11px;color:#999;text-align:center" id="print-foot">
    FreshMart Admin Report · Generated by <?= sanitize(getAdminName()) ?> · <?= date('d M Y H:i') ?>
</div>

<style>
.report-card{background:var(--surface);border:1px solid var(--border);border-radius:var(--radius-lg);padding:20px;box-shadow:var(--shadow)}
.rc-label{font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:1px;color:var(--text3);margin-bottom:7px}
.rc-value{font-family:'Playfair Display',serif;font-size:24px;font-weight:800}
.report-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-bottom:22px}
@media print{
    .no-print{display:none!important}
    .print-only,#print-head,#print-foot{display:block!important}
    .sidebar,.topbar{display:none!important}
    .main{margin-left:0!important}
    .page-content{padding:0!important}
    body{background:#fff!important}
    .card{box-shadow:none!important;border:1px solid #e0e0e0!important}
}
</style>

<?php require_once '../includes/footer.php'; ?>
